default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kima8716
  password: G48rBest
  host: localhost

development:
  <<: *default
  database: quickquill_development

test:
  <<: *default
  database: quickquill_test

production:
  <<: *default
  database: quickquill_production
  username: production_username
  password: <%= ENV['QUICKQUILL_DATABASE_PASSWORD'] %>
